### ISSUE TITLE
Remove XML interface?

### ISSUE THREAD

**Issue by botandrose** [calagator/calagator#121]
Looking at cleaning up the controllers, and I wonder if the XML interface is actually being used by anyone. In my experience, such code is usually a relic from the Rails 2 scaffold days. What do you folks think?

**Comment by botandrose** [comment]
@reidab Feeling this itch again :) Would you mind grepping the production logs for `/ as XML$/`?

**Comment by reidab** [comment]
I really don't see the argument for removing XML support just because it's not trendy anymore. I want our API to be as accessible as possible, and there are still ecosystems for which consuming XML is the most  comfortable solution.

That said, I'd welcome refactoring that moved our controller actions to use ActionController::Responder's `respond_with` and removed any custom rendering blocks for XML.

**Comment by botandrose** [comment]
The impetus to drop XML support is not really a lack of trendiness... I'm motivated by the desire to reduce code complexity. Dropping XML support would slim down Calagator's controllers very significantly, and if its not being used at all then it seems like a clear win. Or in other words, YAGNI?

However, if XML support is something you want to keep regardless of usage, I'll try the `respond_with` route.
