### ISSUE TITLE
Convert to Rails engine

### ISSUE THREAD

**Issue by botandrose** [calagator/calagator#277]
Hey all, some time ago, @reidab and I briefly discussed the idea of converting Calagator from a Rails app to a Rails engine, and I think we're finally in a good position to be able to do this. This would yield many benefits, largely falling into a general category of separating Calagator's stable behavior (Rails engine) from Calagator's highly-variant installation specifics (Rails app). To enumerate:

1. Deployable to Heroku. We currently cannot deploy Calagator to Heroku, because we can't check in Gemfile.lock, because the contents can vary wildly across installations (what version of ruby, what database engine, whether the app is in dev mode or not, etc). By extracting to an engine, consumers of Calagator can easily mount it in their own app with their own Gemfile.lock and configuration, then deploy to Heroku.

2. Make the app composable. Users could install Calagator inside an existing app, instead of needing to fork Calagator to add their own specific pages and functionality.

3. Ease upgrade path to newer versions of Rails. With much less Rails-version-specific code in the repo (e.g. everything in `config/`), upgrading to newer versions of Rails should be much simpler.

4. Support multiple versions of Rails. We'll have to see exactly how easy it is to do this, but its possible in theory, using something like [Appraisal](https://github.com/thoughtbot/appraisal) to verify the different versions.

The big question in my mind is what the repo would look like when this is completed. I see two options:

1. Fork a new repo named `calagator/calagator-core` or something, move the majority of the app into an engine defined there, then include it as a gem in this repo's Gemfile, leaving `calagator/calagator` as just the app shell, only largely useful as the reference installation configuration.

2. Convert this repo to an engine in a gem.

Thoughts on all this?

**Comment by botandrose** [comment]
Just had another thought. It is probably possible to have one repo that is both the enclosing Rails app, and also hosts the Calagator engine gem. We'd have to do something slightly non-standard, like put the engine component in some top level directory other than the project root (e.g. engine/), and have the calagator.gemspec reference those files, but it could work.

**Comment by reidab** [comment]
I think I'm more in favor of migrating this repo to be the engine in a gem, since it more clearly encourages people who want to customize it to create their own apps that depend on the engine. This would obviously require a decent amount of documentation updates, both for development and deployment.

We'd then spin off something like a calagator-portland repo to hold the customizations that were specific to Portland's Calagator instance.

This mirrors what I've done for Open Source Bridge with the [osbridge/openconferenceware](http://github.com/osbridge/openconferenceware) and [osbridge/open-source-bridge-proposals](https://github.com/osbridge/open-source-bridge-proposals) repos.

**Comment by botandrose** [comment]
Awesome, thanks for the guidance... this gives me a direction to go in! I'll see if I can't get something ready for the next Calagator meetup in February.
