### ISSUE TITLE
Spam posting to the RSS feed

### ISSUE THREAD

**Issue by shawnacscott** [calagator/calagator#365]
We've had two separate reports of a large amount of spam posting to the RSS feed lately. This screen shot is an example of one of these spam postings: 
![calagator__events](https://cloud.githubusercontent.com/assets/1648967/7310166/5d9ad418-e9dc-11e4-9bf9-b1e3278848a6.png)

It doesn't appear to me that these events are showing up on the Calagator main page, and I'm unfamiliar with the weed whacking measures we have in place for spam, so I thought I'd bring it up here :)

**Comment by jc00ke** [comment]
I committed some changes to the blacklist a few weeks back but I'm unable to deploy. Those changes should help.

**Comment by reidab** [comment]
There shouldn't be any special sauce that's making spam visible in the RSS feed but not on the site. I'm guessing that this behavior is because RSS readers (especially online ones) keep a cached copy of the feed when they grab it, spam and all. When someone goes to click through to the site, somebody else (often someone who's watching the RSS feed themselves) has already deleted it.

@jc00ke I think those last spam changes got deployed if they were committed before the engine transition. If they came in after that, I can port them over and deploy them soon.

**Comment by jc00ke** [comment]
@reidab they were committed after, into calagator.org's [blacklist](https://github.com/calagator/calagator.org/commits/master/config/blacklist.txt)

**Comment by reidab** [comment]
I've manually deployed these changes to the calagator.org instance.
