### ISSUE TITLE
RSS feed not in calendar order

### ISSUE THREAD

**Issue by keithlofstrom** [calagator/calagator#493]
The RSS feed seems to display in event creation order, not chronological calendar order.  For example, the attached image of the feed on my protopage shows 7 entries for "Ruby Coworking", in reverse order from February 25 to January 14, pushing other events off the bottom of the queue.  This behavior is the same on different linux machines using both Firefox and Chrome, though all use protopage to display the RSS.

This may be PEBKAC, or incompetence, or ignorance of RSS.  Heck, I don't even know how to ork a cow.

![calagatorrss](https://cloud.githubusercontent.com/assets/16678370/12310730/bdae6964-ba06-11e5-8995-c11bb1832d6a.png)

**Comment by reidab** [comment]
The feeds are meant as a way for people to keep up with newly-posted events, so this is somewhat by design. We use the creation time of the event to populate the Atom _published_ attribute, which most RSS readers use for ordering. That said… when I actually look at the contents of http://calagator.org/events.atom, the items in the file are in calendar order. 

If you're looking for a way to display events in calendar order, the RSS feed contains _start_time_ attributes, which could be used for sorting. Otherwise, I'd look into consuming the ICS feed instead. :smile:
