### ISSUE TITLE
Calagator with Devise

### ISSUE THREAD

**Issue by DeodorantMan** [calagator/calagator#496]
I am trying to integrate Devise into this library, however I am getting an error 
```
NameError in Calagator::Site#index
undefined local variable or method `edit_user_registration_path'
```

my routes file looks like this:
```
Rails.application.routes.draw do
  mount Calagator::Engine, :at => '/'
  devise_for :users
end
```

When I do `rake routes` I can see that the route is there
```
edit_user_registration GET    /users/edit(.:format)          devise/registrations#edit
```

Any help would be appreciated. Thanks

**Comment by reidab** [comment]
Since Calagator is a mountable [Rails Engine](http://guides.rubyonrails.org/engines.html), it has its own set of routes. The [Routes section](http://guides.rubyonrails.org/engines.html#routes) of the Engines guide touches on this a bit. 

Calling `devise_for` adds routes to your app's router, but when you call `edit_user_registration_path` from a Calagator view, it's going to try looking it up in Calagator's router. You should be able to get around this by being a little more explicit and calling `main_app.edit_user_registration_path` to get at the main app's routes.

**Comment by DeodorantMan** [comment]
That was quick. Thanks! It works like a charm.
