### ISSUE TITLE
sharing events to pdxactivist.org

### ISSUE THREAD

**Issue by vjpdx** [calagator/calagator#526]
Is there any way to share events between calagator & pdxactivist? Because, important. 

I know that pdxactivist was built using calagator. I've tried importing an event from calagator to pdxactivist via their Import/slurp - no luck. Am I just out of luck?

Yours, vj, who's trying to build a tower of babel made of Portland activist events - [Portland Resistance Calendar](http://kboo.fm/resist) & populating [pdxactivist](https://pdxactivist.org/)

**Comment by reidab** [comment]
In theory, pasting a URL like http://calagator.org/events/1250471594 into https://pdxactivist.org/sources/new should work due to the hCalendar and microformats2 markup in the page. That said, it doesn't seem to be working. 😭

What should work at the moment is importing the iCalendar representation of an event, like http://calagator.org/events/1250471594.ics
