### ISSUE TITLE
Getting "Unable to find any upcoming events to import from this source" error

### ISSUE THREAD

**Issue by aeschright** [calagator/calagator#71]
Transferred from https://code.google.com/p/calagator/issues/detail?id=475

What steps will reproduce the problem?
1. Cleared cookies and tried private browsing before going to "Import events" page
2. Tried to bulk upload this iCal feed (http://www.google.com/calendar/ical/p3cbgpr03ofq2lngffkn333u20%40group.calendar.google.com/public/basic.ics)
2. Get this error ("Unable to find any upcoming events to import from this source")

What is the expected output? What do you see instead?
Expected to import events, as this has worked many times successfully in the past.

What browser are you using? On what operating system?
Chrome Version 33.0.1750.146 & Iceweasel 24.3.0 on Xubuntu Linux 12.04

**Comment by reidab** [comment]
On our current code base, this calendar imports successfully.

That said, it takes upwards of seven minutes to do so because it contains every FreeGeek event going back to 2008. After doing all of that, it only imports the 14 upcoming events. We parse everything and then wait until the very end to throw out old events, so it may be worth profiling the import process to find out if the majority of the time is spend in our code or in the underlying ICS parser.

**Comment by reidab** [comment]
Spawned #481 to track the import slowness.
